live_config_reload = true

[font]
size = 14.0

[font.bold]
family = "SFMono Nerd Font"
style = "Regular"

[font.bold_italic]
family = "SFMono Nerd Font"
style = "Italic"

[font.italic]
family = "SFMono Nerd Font"
style = "Italic"

[font.normal]
family = "SFMono Nerd Font"
style = "Regular"

[cursor]
style = 'Underline'
unfocused_hollow = true

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Option"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Option"

[[keyboard.bindings]]
chars = "\u0001"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0005"
key = "Right"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[scrolling]
history = 100000

[window]
decorations = "transparent"
dynamic_padding = false
opacity = 1
startup_mode = "Windowed"
title = "Alacritty"

[window.dimensions]
columns = 150
lines = 40

[window.padding]
x = 5
y = 25

[window.position]
x = 350
y = 200

[colors.primary]
background = '#0A0E14'
foreground = '#B3B1AD'

[colors.normal]
black   = '#01060E'
red     = '#EA6C73'
green   = '#91B362'
yellow  = '#F9AF4F'
blue    = '#53BDFA'
magenta = '#FAE994'
cyan    = '#90E1C6'
white   = '#C7C7C7'

[colors.bright]
black   = '#686868'
red     = '#F07178'
green   = '#C2D94C'
yellow  = '#FFB454'
blue    = '#59C2FF'
magenta = '#FFEE99'
cyan    = '#95E6CB'
white   = '#FFFFFF'
