[font]
size = 16.0

[font.bold]
family = "SFMono Nerd Font"
style = "Bold"

[font.normal]
family = "SFMono Nerd Font"
style = "Medium"

[cursor.style]
shape = "Underline"

[window]
decorations = "Full"
opacity = 1.0

[window.dimensions]
columns = 150
lines = 30

[window.position]
x = 300
y = 240

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Option"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Option"

[[keyboard.bindings]]
chars = "\u0001"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0005"
key = "Right"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"
