[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Medium"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[cursor.style]
shape = "Underline"

[window]
decorations = "Buttonless"
option_as_alt = "Both"

[window.dimensions]
columns = 150
lines = 30

[window.position]
x = 300
y = 240

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Option"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Option"

[[keyboard.bindings]]
chars = "\u0001"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0005"
key = "Right"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
key = "N"
mods = "Command"
action = "CreateNewWindow"

[[keyboard.bindings]]
key = "W"
mods = "Command"
action = "Quit"

[colors.primary]
background = "#000000"
foreground = "#FFFFFF"
