import = ["/Users/home/.config/alacritty/themes/themes/tomorrow_night_bright.toml"]
live_config_reload = true

[font]
size = 14.0

[font.bold]
family = "SFMono Nerd Font"
style = "Regular"

[font.bold_italic]
family = "SFMono Nerd Font"
style = "Italic"

[font.italic]
family = "SFMono Nerd Font"
style = "Italic"

[font.normal]
family = "SFMono Nerd Font"
style = "Regular"

[cursor]
style = 'Beam'

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Option"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Option"

[[keyboard.bindings]]
chars = "\u0001"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0005"
key = "Right"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[scrolling]
history = 100000

[window]
decorations = "transparent"
dynamic_padding = false
opacity = 1
startup_mode = "Windowed"
title = "Alacritty"

[window.dimensions]
columns = 150
lines = 40

[window.padding]
x = 5
y = 25

[window.position]
x = 350
y = 200
