[env]
TERM = "xterm-256color"

[font]
size = 20.0

[font.bold]
family = "SFMono Nerd Font"
style = "Regular"

[font.normal]
family = "SFMono Nerd Font"
style = "Regular"

[font.glyph_offset]
x = 0
y = 0

[cursor.style]
shape = "Block"
blinking = "Never"

[cursor.vi_mode_style]
shape = "Underline"
blinking = "Never"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Option"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Option"

[[keyboard.bindings]]
chars = "\u0001"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0005"
key = "Right"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[scrolling]
history = 100000
multiplier = 1

[window]
decorations = "none"
dynamic_padding = true
opacity = 0.9
startup_mode = "Maximized"
title = "Alacritty"

[window.padding]
x = 0
y = 0

[window.position]
x = 350
y = 200

[colors.primary]
background = '#000000'
foreground = '#ffffff'

[colors.normal]
black   = '#000000'
red     = '#cd0000'
green   = '#00cd00'
yellow  = '#cdcd00'
blue    = '#0000ee'
magenta = '#cd00cd'
cyan    = '#00cdcd'
white   = '#e5e5e5'

[colors.bright]
black   = '0x7f7f7f'
red     = '0xff0000'
green   = '0x00ff00'
yellow  = '0xffff00'
blue    = '0x5c5cff'
magenta = '0xff00ff'
cyan    = '0x00ffff'
white   = '0xffffff'
